### ISSUE TITLE
Allow workflow yaml to define type of input files

### ISSUE THREAD

**Issue by pcm32** [phnmnl/wft4galaxy#11]
Sometimes Galaxy doesn't handle the auto detection of file types based on extensions. For instance, when uploading a zip file, Galaxy tends to uncompress it unless that you actively set the zip type on upload. We need an equivalent facility when setting input files, like:

```yaml
inputs:
      "exchange": "exchanged_file.csv"
      ZipData: 
          file: "wd.zip"
          type: "zip"
      "tracingModel": "tracing_model.csv"
      "SBMLmodel": "sbml_model.sbml"
      "constraints": "constraints.csv"
```

This needs of course to be handled so that a the file is uploaded as a zip (like when doing the upload manually and setting zip in this case).

Thanks!
