### ISSUE TITLE
specify input format

### ISSUE THREAD

**Issue by korseby** [phnmnl/wft4galaxy#17]
Hi all,

Wenn running a test-workflow, I'm getting the following error message:

```
2017-03-23 09:43:10,809 INFO: Workflow '_WorkflowTest_soap-nmr (imported from API)' (id: ebfb8f50c6abde6d) running ...
2017-03-23 09:43:19,228 ERROR: Runtime error: 964b37715ec9bd22 (Dataset Matrix used for statistics.): Specify a dataset of the required format / build.
2017-03-23 09:43:19,325 ERROR: Runtime error: 964b37715ec9bd22 (Dataset Matrix used for statistics.): Specify a dataset of the required format / build.
```

This is because Galaxy does not detect the input file format correctly. I have to manually specify CSV when importing the data into Galaxy.

So, this issue is more like a feature request. Can you implement the option to define a format for the inputfiles and outputfiles in the yaml?

@c-ruttkies This could be interesting for you as well.

**Comment by kikkomep** [comment]
Hi!
Actually, this feature already exists: see #11 and #13.

**Comment by ilveroluca** [comment]
It's a recent addition.  Maybe @korseby is using an older version.  So update your version of wft4galaxy :-)

**Comment by korseby** [comment]
Ah thanks. :)

I'm using the docker version. So it should be the latest. Couldn't find it in the documentation, though.

**Comment by korseby** [comment]
Still do not have luck with the latest docker-version.

I am starting wft4galaxy with:
`wft4galaxy-docker -f "soap-nmr.yml" -m develop -e wft4galaxy --enable-logger`

Here's the yaml:
```
##########################################################################################
#  Global settings
##########################################################################################
enable_logger: True
enable_debug: True
output_folder: "results"

##########################################################################################
#  Workflow tests
##########################################################################################
workflows:
  # workflow test "soap-nmr"
  change_case:
    file: "soap-nmr.ga"
    inputs:
      spectrafile:
        file: "inputs/test_data_spectra.csv"
        type: "csv"
      ppmfile:
        file: "inputs/test_data_ppm.csv"
        type: "csv"
      fidfile:
        file: "inputs/test_data_fid.csv"
        type: "csv"
    expected:
      output:
        file: "outputs/test_data_set.csv"
        type: "csv"
```
